# Generated by Django 3.1.5 on 2021-01-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_conference_room_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_conference_room_booking_app.room')),
            ],
            options={
                'unique_together': {('date_of_booking', 'id_room')},
            },
        ),
    ]
