# Generated by Django 3.1.5 on 2021-01-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_conference_room_booking_app', '0002_bookingroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingRoom',
            new_name='Booking',
        ),
    ]
