# Generated by Django 3.1.5 on 2021-01-28 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_conference_room_booking_app', '0003_auto_20210127_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateField(default=datetime.date(2021, 1, 28)),
        ),
    ]
